name: Flutter Web
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps: 
        - name: Checkout
          uses: actions/checkoutl@v2

        - name: Setup Flutter
          uses: subosito/flutter-action@v1
          with:
            channel: 'beta'

        - name: Enable Flutter web
          run: flutter config --enable-web

        - name: Install dependencies
          run: flutter packages get

        - name: Build web
          run: flutter build web

        - name: Deploy
          run: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.token }}
            publish_dir: ./build/web